---
- hosts: clients
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Actualitzaci贸 dels paquets
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Instal路lar ProFTPd
      apt: name=proftpd update_cache=yes state=latest

    - name: Instal路lar OpenSSL
      apt: name=openssl update_cache=yes state=latest

    - name: Copiar l'arxiu de configuraci贸
      template:
        src: "files/proftpd.conf"
        dest: "/etc/proftpd/proftpd.conf"
      notify: Restart ProFTPd

    - name: Copiar certificat
      template:
        src: "files/cert.crt"
        dest: "/etc/ssl/certs/cert.crt"

    - name: Copiar clau
      template:
        src: "files/cert.key"
        dest: "/etc/ssl/private/cert.key"

    - name: Copiar arxiu tls
      template:
        src: "files/tls.conf"
        dest: "/etc/proftpd/tls.conf"
      notify: Restart ProFTPd

  handlers:
    - name: Reload ProFTPd
      service:
        name: proftpd
        state: reloaded

    - name: Restart ProFTPd
      service:
        name: proftpd
        state: restarted
